### PR TITLE
Fix markdown styles

### LINKED ISSUE #51: All of our markdown stylings went away?
image

All of a sudden h1s, h2s, etc. in the body of descriptions are no longer styled.

### PR DESCRIPTION
**Pull request by marcusmoore**
This PR fixes our markdown styles by using applying the GitHub stylesheet to our readme and description sections.

image

Closes #51

### CODE REVIEW

**Comment by mattstauffer** [comment]
@marcusmoore Thank you!!

... Do you know why it broke in the first place?!

**Comment by marcusmoore** [comment]
@mattstauffer I _think_ it was something in #35.

**Comment by mattstauffer** [comment]
@marcusmoore it's so weird, because at least that commit doesn't change any source files. I think I still want to make sure i know WHICH change to our source files made it go away--I'll try to dig into that whole PR later.

File: app/ReadmeFormatter.php [hunk 1]
```diff
@@ -42,6 +44,11 @@ public function formatHtml($html)
         return '<div class="markdown">'.$formattedHtml.'</div>';
     }
 
+    private function removeAnchors($text)
+    {
+        return preg_replace('/<a .+class=\"anchor\".+>.+<\/a>/i', '', $text);
```
Comment (jakebathman) [inline app/ReadmeFormatter.php:49]: Should add some lazy quantifiers here to narrow potential matches. Example: https://regex101.com/r/hNuMQx/1
```suggestion
        return preg_replace('/<a .*?class=\"anchor\".*?>.*?<\/a>/i', '', $text);
```

File: app/ReadmeFormatter.php [hunk 2]
```diff
@@ -74,13 +81,13 @@ public function replaceImageUrlsHtml($html)
 
     public function replaceNonImageUrlsHtml($html)
     {
-        $pattern = '/<a href="((?!http)(?!mailto).*?)"/i';
+        $pattern = '/<a(.+)href="((?!http)(?!mailto).*?)"/i';
```
Comment (jakebathman) [inline app/ReadmeFormatter.php:84]: Also a lazy quantifier here to prevent over-matching. Example: https://regex101.com/r/jFUceC/2
```suggestion
        $pattern = '/<a(.+?)href="((?!http)(?!mailto).*?)"/i';
```

File: resources/assets/js/components/PackageDetail.vue [hunk 3]
```diff
@@ -164,3 +164,21 @@ export default {
     },
 };
 </script>
+
+<style scoped>
```
Comment (jakebathman) [inline resources/assets/js/components/PackageDetail.vue:168]: Before we merge, we should probably move these to a CSS file, unless there's a reason they should be inside the component? I've never used scoped CSS before, but I wouldn't think to look for these styles here in the future.

File: app/ReadmeFormatter.php (hunk 1 above)
Comment (marcusmoore) [reply app/ReadmeFormatter.php]: Good thinking and thanks for the suggestions. I've applied them in commit.

File: resources/assets/js/components/PackageDetail.vue (hunk 3 above)
Comment (marcusmoore) [reply resources/assets/js/components/PackageDetail.vue]: Good thinking. I pull this snippet from a component in another Tighten project and didn't think about it too much. I moved it to our custom css file and removed some unneeded rules.

**Comment by marcusmoore** [comment]
@mattstauffer I dug a little deeper. It looks like this is actually [the commit](https://github.com/tightenco/novapackages/pull/35/commits/fbcbc63e94e74eb2239284b2359bf6878894611a) where styling goes away. Still in the same PR but it's the first commit instead of the last one like I linked earlier.

| Commit | Screenshot |
|-|-|
| [Tweak shadows and round cards on homepage](https://github.com/tightenco/novapackages/commit/1a760752aaddbd6e7f74abed27d3739f1c818a4e) | image |
| [Upgrade Tailwind](https://github.com/tightenco/novapackages/commit/fbcbc63e94e74eb2239284b2359bf6878894611a) | image |

**Comment by mattstauffer** [comment]
OHHHHH.. so those were just relying on native heading and bullet stylings in Tailwind. Got it!

File: app/ReadmeFormatter.php [hunk 4]
```diff
@@ -24,6 +24,8 @@ public function __construct($package)
 
     public function format($text)
     {
+        $text = $this->removeAnchors($text);
```
Comment (mattstauffer) [inline app/ReadmeFormatter.php:27]: Why are we removing these? Are they not useful? Thanks!

**Comment by dillingham** [comment]
any hopes of the fixes? 😇

**Comment by marcusmoore** [comment]
@dillingham planning on wrapping this up later this week 😄

File: app/ReadmeFormatter.php (hunk 4 above)
Comment (marcusmoore) [reply app/ReadmeFormatter.php:27]: image

My memory is a little fuzzy but I realized that anchors within an html readme link to a broken link.

The link highlighted in the screenshot above is
`https://github.com/timothyasp/nova-badge-field/blob/master/#laravel-nova-badge-field` and `blog/master/` should not be included in it.

Markdown formatted readmes do not have anchors for titles so I figured stripping them would be a good move. Alternatively we could probably add anchors to markdown readmes but I don't think many people would utilize that feature.

Comment (mattstauffer) [reply app/ReadmeFormatter.php:27]: OK, sounds good. I think we can consider re-adding them later in a way that works, but good for me for now.
